2020-05-07 18:59:19,698 - logs… - INFO - 接口测试用例：test_api_02_01.py  ====== test  start ========
2020-05-07 18:59:19,807 - logs… - INFO - (200, {'errcode': 0, 'data': {'furnaceNo': '2', 'content': [1054.0, 984.0, 960.0, 987.0, 1163.0, 835.0], 'furnace_count': 10}})
2020-05-07 18:59:19,807 - logs… - INFO - 请求码为： 200
2020-05-07 18:59:19,807 - logs… - INFO - errcode\data  字段存在
2020-05-07 18:59:19,807 - logs… - INFO - furnaceNo\content\furnace_count  字段存在
2020-05-07 18:59:19,880 - logs… - INFO - (200, {'errcode': 0, 'data': {'furnaceNo': 2, 'areaNo': '1', 'status': 1, 'content': [], 'furnace_count': 10, 'area_count': '6', 'door_status': 1, 'target_temp': 1200}})
2020-05-07 18:59:19,880 - logs… - INFO - 所获取指定炉的炉区域为： 6
2020-05-07 18:59:19,880 - logs… - INFO - 显示对应区域数时间温度数据
2020-05-07 18:59:19,880 - logs… - INFO - 温度数据类型不正确
2020-05-07 18:59:19,881 - logs… - INFO - test_api_02_01.py : File
